saucelabs/visual-sdks

- visual-dotnet/SauceLabs.Visual/VisualApi.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
Simplify VisualClient Interface
Hide `CreateBuild`/`FinishBuild` build logic as it's not necessary for customer.
Expose `Build` through  `VisualClient`.
Rely on `IDisposable` interface.
> Simplify VisualClient Interface

- visual-dotnet/SauceLabs.Visual/SauceLabs.Visual.csproj
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
> Use Polly instead of AnyRetry

- visual-dotnet/SauceLabs.Visual/CreateBuildOptions.cs
- visual-dotnet/SauceLabs.Visual/GraphQL/CreateBuild.cs
- visual-dotnet/SauceLabs.Visual/GraphQL/CreateBuildIn.cs
- visual-dotnet/SauceLabs.Visual/GraphQL/CreateBuildMutation.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
> IRIS-835
Add support for `DefaultBranch`
> Add support for DefaultBranch

- visual-dotnet/SauceLabs.Visual/VisualClient.cs
Adds `VisualClient.Create()` static method.
In order to avoid `.Result` or `.Wait` in synchronous areas, provide a `static Create()` routine that will be explicitely async.
> Provide static VisualClient.Create

- visual-dotnet/SauceLabs.Visual.Tests/VisualApiTest.cs
- visual-dotnet/SauceLabs.Visual/GraphQL/CreateSnapshotFromWebDriverIn.cs
- visual-dotnet/SauceLabs.Visual/Utils/GraphQLResponseExtension.cs
- visual-dotnet/SauceLabs.Visual/Utils/StringUtils.cs
- visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
> Issue : IRIS-834
- Exposes fields to set context
- Move classes from `public` to `internal` as they should not be exposed
- Expose `CurrentTestName` & `CurrentClassName` so it can be overridden by user.
> Add Current Test/Class elements

- visual-dotnet/SauceLabs.Visual.Tests/BuildFactoryTest.cs
- visual-dotnet/SauceLabs.Visual.Tests/VisualApiTest.cs
- visual-dotnet/SauceLabs.Visual/ApiBuildPair.cs
- visual-dotnet/SauceLabs.Visual/BuildFactory.cs
- visual-dotnet/SauceLabs.Visual/Region.cs
- visual-dotnet/SauceLabs.Visual/VisualApi.cs
- visual-dotnet/SauceLabs.Visual/VisualBuild.cs
- visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
> Issue : IRIS-856
Currently build is created (or loaded) upon creation of the `VisualClient`.
This PR comes to persist the newly created build, thus allowing multiple class to be reported within the same `VisualBuild`.
As a consequence, the `Cleanup` will need to be moved out of the test AfterAll, but to a global AfterAll.
Additionally:
- Fixes a bug in the `TextContext` implementation
- Removes dependency of `VisualApi` to `WebDriver` as it's never used
> Ensure build is shared across all test classes

- visual-python/src/saucelabs_visual/client.py
Extends the default GQL client to match API services.
> [Python] Extend default GQL timeout

- visual-dotnet/SauceLabs.Visual/BuildFactory.cs
Fixes `NullReferenceException` when buildId or customId is not found.
> Issue : IRIS-924
`NullReferenceException` occurs when `buildId` or `customId` specified is invalid.
> bugfix: .Net / NullReferenceException when buildId or customId is not found

- visual-python/src/saucelabs_visual/frameworks/robot.py
Tweaks / fixes a few ignore region parsing errors when element rects could have return non integer values
> [Python] Fix non-integer values in WebElement rects

- visual-dotnet/SauceLabs.Visual/Utils/DiffingOptionsInHelper.cs
- visual-dotnet/SauceLabs.Visual/VisualCheckDiffingOptions.cs
- visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
Replaces `EnableOnly` / `DisableOnly` by `DiffingOption` to be sure only one is set.
- Breaking-change
> .NET: Enhance VisualCheckOptions

- visual-java/src/main/java/com/saucelabs/visual/CheckOptions.java
- visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
- visual-java/src/main/java/com/saucelabs/visual/model/FullPageScreenshotConfig.java
- visual-java/src/test/java/com/saucelabs/visual/SmokeTest.java
Add new fps options into java bindings
Configuration change
> IRIS-927-align-java-fps-options

- visual-dotnet/SauceLabs.Visual/FullPageConfig.cs
- visual-dotnet/SauceLabs.Visual/GraphQL/FullPageConfigIn.cs
fps extend available options
New feature (non-breaking change which adds functionality)
> IRIS-928-fps-extend-c-sharp-options

- visual-js/.changeset/soft-shirts-destroy.md
- visual-js/visual-cypress/src/commands.ts
- visual-js/visual-cypress/src/index.ts
- visual-js/visual-cypress/src/types.ts
Fixes DPR computation in cypress. All (ignore) region coordinates are expected in DOM pixels without DPR applied. DPR is applied by the backend now.
> Issue : IRIS-997
> Let backend handle device pixel ratio in cypress

- visual-python/integration-tests/robot/integration/__init__.robot
- visual-python/integration-tests/robot/integration/clipping.robot
- visual-python/integration-tests/robot/integration/full_page_screenshot.robot
- visual-python/integration-tests/robot/integration/ignore_regions.robot
- visual-python/requirements/user.txt
- visual-python/src/saucelabs_visual/client.py
- visual-python/src/saucelabs_visual/frameworks/robot.py
- visual-python/src/saucelabs_visual/typing.py
- visual-python/src/saucelabs_visual/utils.py
Adds WebElement support to both Robot Framework and the standard library. Allows passing IgnoreElementRegions with a `WebElement` or `WebElement[]` in the `element` field. 
> [Python] WebElement Support (Robot & No Framework)

- visual-dotnet/SauceLabs.Visual/Region.cs
- visual-dotnet/SauceLabs.Visual/Utils/EnvVars.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
This pull request adds region support to C# SDK.
Since we have support for username, and password, we don't need to require sauce region if it is already there. Most of the time our examples require sauce region to be available. Our users also most likely have them 
New feature (non-breaking change which adds functionality)
[x] support ignore regions via env variables
-
> Allow to define region via env variables.

- visual-python/src/saucelabs_visual/client.py
Allows externally created / managed builds to be used in Python / Robot.
> [Python] Allow externally created builds in Python / Robot

- visual-dotnet/SauceLabs.Visual/BaselineOverride.cs
- visual-dotnet/SauceLabs.Visual/CreateBuildOptions.cs
- visual-dotnet/SauceLabs.Visual/GraphQL/BaselineOverrideIn.cs
- visual-dotnet/SauceLabs.Visual/GraphQL/CreateSnapshotFromWebDriverIn.cs
- visual-dotnet/SauceLabs.Visual/Models/Browser.cs
- visual-dotnet/SauceLabs.Visual/Models/OperatingSystem.cs
- visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
Adds the ability to override the baseline matching behavior at a build or visual check level.
> [C#] Add baselineOverride functionality

- visual-python/Dockerfile
- visual-python/integration-tests/robot/integration/cross_browser.robot
- visual-python/requirements/dev.txt
- visual-python/src/saucelabs_visual/client.py
- visual-python/src/saucelabs_visual/frameworks/robot.py
- visual-python/src/saucelabs_visual/typing.py
Adds a few updates to the Visual Python & Robot Framework binding:
- Adds support for baseline overrides / cross browser / os comparisons
- Adds the ability to configure global client options to avoid setting the same setting on every snapshot for the following
- dom capture
- baseline overrides
- diffing method
- full page config
- Adds RDC support for SauceLabs by forwarding the Job ID from the driver results
> [Python] Baseline Overrides / Mobile support

- .github/workflows/js-build.yml
- visual-js/.changeset/afraid-balloons-brush.md
- visual-js/visual/src/common/api.ts
- visual-js/yarn.lock
> Issue : IRIS-1234
Example in storybook context:
```
● Example/Page › Logged In › play-test
Uploading snapshot reached timeout.
Please check that you have connectivity and are able to do HTTP PUT requests.
URL: https://storage.googleapis.com/sauce-iris-prod-us-west4-ybyc/orgs/[orgId]/e4ea0fd1-21ba-4397-ac45-202a41f094f9.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=sauce-svc-iris-bucket-prod%40sauce-production-p-i0l6.iam.gserviceaccount.com%2F20240910%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240910T120018Z&X-Goog-Expires=900&X-Goog-SignedHeaders=content-type%3Bhost&response-content-disposition=attachment&X-Goog-Signature=[SIG]
Note: This URL is valid only for a couple of minutes
16864 |       if (ex?.name === "AbortError") {
16865 |         console.error();
> 16866 | …
```
> Enhance timeout upload

- visual-js/.changeset/slow-seas-occur.md
- visual-js/visual-cypress/src/index.ts
Our [docs](https://docs.saucelabs.com/visual-testing/integrations/cypress/#test-results-summary) say you can use the sauceVisualResult summary to check the status of a result and assert that a certain status is never found. Currently, however, that object is empty so asserting `unapproved = 0` would never pass. 
This PR does the following:
- This updates the check to populate all the keys of our DiffStatus into the initial value before reducing over the nodes.
- This also bumps all other bindings by a patch to roll out the new server-side ignore region calculation.
> [Cypress] Ensure all statuses are available in `sauceVisualResult` summary

- visual-dotnet/SauceLabs.Visual/Utils/EnvVars.cs
Disables nullish coalescing of empty strings during ENV parsing. Since null values from ENVs were coalesced to empty strings `""` these would be sent to the GraphQL API and stored with the corresponding build / snapshot. This is especially problematic for custom IDs which are used as a grouping behavior for builds and can be easily done unintentionally with the current behavior.
Project / Branches are coalesced to empty strings before hashing in the backend which should make this backwards compatible for baseline hash matching.
> [C#] Disable nullish coalescing to empty strings in ENV

- visual-js/.changeset/old-mails-sin.md
- visual-js/visual-cypress/src/commands.ts
Iterates over passed cypress chainables and yields the results in an array.
Example of multiple ignorables:
```js
cy.sauceVisualCheck('Inventory Page', {
captureDom: true,
ignoredRegions: [
cy.get('.inventory_item_price'),
cy.get('.btn_inventory'),
cy.get('.inventory_item_name'),
cy.get('.bm-burger-button'),
cy.get('img.inventory_item_img'),
{
x: 50,
y: 50,
width: 100,
height: 100,
}
],
});
```
Results in UI:
> [Cypress] Allow multiple elements in ignoreRegions

- visual-js/.changeset/tricky-pandas-doubt.md
- visual-js/visual-cypress/package.json
- visual-js/visual-cypress/src/commands.ts
- visual-js/yarn.lock
Updates the type exported from our plugin and recommended in our documentation to add the `saucelabs` key to the Cypress configuration object. Enables better TypeScript support when running / configuring Cypress under a TypeScript project. Also moves a devdependency to the correct location in package.json.
> [Cypress] Augment types to better support TypeScript Cypress configurations

- visual-js/.changeset/five-monkeys-live.md
- visual-js/visual-playwright/src/api.ts
This updates the ignore regions position using the offset of the clipped element, if present, for Playwright + Storybook.
Example from Sauce Demo site: 
> [Playwright] Fix ignore region positioning when clipSelector is also present

- visual-js/.changeset/curvy-foxes-watch.md
- visual-js/visual-wdio/src/SauceVisualService.ts
- visual-js/visual-wdio/src/guarded-types.ts
- visual-js/visual/src/graphql/__generated__/graphql.ts
- visual-js/visual/src/utils.ts
- visual-js/yarn.lock
expose ignore region selectors for mobile native full page screenshot
> wdio - ignore selectors

- visual-js/.changeset/tender-turkeys-divide.md
- visual-js/visual-storybook/package.json
- visual-js/visual-storybook/src/api.ts
- visual-js/visual-storybook/src/index.ts
- visual-js/visual-storybook/src/types.ts
- visual-js/yarn.lock
This PR adds the ability to test additional variations of a story by supplying custom args which will be appended to the initial args state prior to each capture. For example, you could have a single Storybook Story with a `Button` component with controls to toggle the `size` and `primary` props so users could see the story in their playground and still take snapshots of each state.
With that example, here we could have a single Story to not clutter the UI, but still take snapshots of numerous states when using Sauce Visual. Below tests numerous size, disabled, and primary states. Each `StoryVariation` allows customizing the name and overriding the args for a story. It will reset the args to the default `initialArgs` state prior to each snapshot variation.
See the …
> [Storybook] Add ability to auto capture variations of a Story

- visual-js/.changeset/forty-bobcats-raise.md
- visual-js/visual-storybook/package.json
- visual-js/visual-storybook/src/api.spec.ts
- visual-js/visual-storybook/src/api.ts
- visual-js/visual-storybook/tsconfig.json
> [Storybook] Fix postfixing of name when adding storybook variations

- visual-js/.changeset/mean-pans-film.md
- visual-js/visual-storybook/.gitignore
- visual-js/visual-storybook/package.json
- visual-js/visual-storybook/src/api.ts
- visual-js/visual-storybook/src/index.ts
- visual-js/visual-storybook/src/play.ts
- visual-js/visual-storybook/src/types.ts
- visual-js/visual-storybook/src/types/global.d.ts
- visual-js/yarn.lock
This PR adds the ability to take snapshots _during_ Storybook play interactions, instead of just at the end. This also reintroduces Storybook 6 support by tweaking dependency requirements.
For example, you could now open a dropdown, focus an input field, type text to generate form errors all while taking snapshots at each step of the way to catch all visual edge cases without creating individual stories for each.
This requires a new `preVisit` hook which has to be added to the Storybook test runner configuration. If attempting to use the `takeVisualSnapshot` without it, it will throw an error and mention this new addition.
> [Storybook] Add ability to take snapshots during Storybook `play` interactions

- visual-dotnet/SauceLabs.Visual/GraphQL/CreateSnapshotFromWebDriverIn.cs
- visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
- visual-java/src/main/graphql/visual/createSnapshotUpload.graphql
- visual-java/src/main/graphql/visual/schema.graphqls
- visual-java/src/main/java/com/saucelabs/visual/graphql/CreateSnapshotFromWebDriverMutation.java
- visual-js/.changeset/nine-berries-battle.md
- visual-js/visual/src/graphql/__generated__/graphql.ts
- visual-js/visual/src/types.ts
- visual-python/src/saucelabs_visual/client.py
> Issue : IRIS-1373
Removes deprecated fields from the GraphQL client.
> Update GraphQL schema

- visual-js/.changeset/spotty-pumpkins-hide.md
- visual-js/visual-playwright/src/api.ts
Offsets the ignore region & clip calculation with the current scroll offset on the window
Before:
After:
> [Playwright] Fix ignore region & clip positioning when page is scrolled prior to snapshot

- visual-js/visual-snapshots/src/api/visual-snapshots-api.ts
- visual-js/visual-snapshots/src/app/pdf-handler.ts
- visual-js/visual-snapshots/src/commands/options.ts
- visual-js/visual-snapshots/src/commands/pdf.ts
- visual-js/visual-snapshots/src/commands/validate.ts
- visual-js/visual-snapshots/src/utils/format.ts
- visual-js/visual-snapshots/test/api/__snapshots__/visual-api.spec.ts.snap
- visual-js/visual-snapshots/test/api/visual-api.spec.ts
- visual-js/visual-snapshots/test/utils/format.spec.ts
> Issue : INT-20
Adds the following options to CLI:
* `--test-name`
* `--suite-name`
* `--snapshot-name`
* `--build-id` - it was ignored before
> [INT-20] Additional CLI options for PDF upload

- visual-js/visual-cypress/integration-tests/tsconfig.json
When running `npm run login-test` in `visual-cypress/integration-tests`, an error is shown:
```
Error: Webpack Compilation Error
[tsl] ERROR
TS5109: Option 'moduleResolution' must be set to 'Node16' (or left unspecified) when option 'module' is set to 'Node16'.
```
> visual-js: fix visual-cypress build error

- visual-js/visual-storybook/.eslintrc.cjs
- visual-js/visual-storybook/integration-tests/src/index.tsx
- visual-js/visual-storybook/integration-tests/src/stories/Page.tsx
- visual-js/visual-storybook/integration-tests/tsconfig.json
- visual-js/visual-storybook/tsconfig.lint.json
When running `npm run storybook` in `visual-storybook/integration-tests`, lint errors appear. Additionally, ESLint throws errors about invalid configuration (not all files are included by `tsconfig.json`).
> visual-js: fix visual-storybook lint errors

- visual-js/package-lock.json
- visual-js/visual-snapshots/.eslintrc.cjs
- visual-js/visual-snapshots/.gitignore
- visual-js/visual-snapshots/README.md
- visual-js/visual-snapshots/jest.config.cjs
- visual-js/visual-snapshots/package.json
- visual-js/visual-snapshots/tsconfig.json
- visual-js/visual-snapshots/tsconfig.src.json
- visual-js/visual-snapshots/tsconfig.test.json
> Issue: INT-1
Changes `tsconfig.json` configurations so test files are typechecked, but not emitted to the `lib` directory.
Several config files we're required to be added or changed:
* `tsconfig.src.json` - emits source files to `lib`
* `tsconfig.test.json` - typechecks test files
* `tsconfig.json` - references `tsconfig.src.json` and `tsconfig.test.json` files
> [INT-1] visual-snapshots: do not emit test files to build directory

- visual-js/visual-snapshots/src/app/worker/worker-pool-pdf-snapshot-uploader.ts
Do not use `import.meta.dirname` which requires node >= 20.11
> [no-ticket] node 18 support

- visual-js/visual-snapshots/src/app/pdf-handler.ts
- visual-js/visual-snapshots/src/commands/pdf.ts
If snapshot creation fails, we should finish the created build
> [no-ticket] always finish created builds

- visual-js/.changeset/forty-bees-sin.md
- visual-js/visual-snapshots/src/app/pdf-handler.ts
- visual-js/visual-snapshots/src/commands/pdf.ts
- visual-js/visual-snapshots/src/utils/glob.ts
- visual-js/visual-snapshots/test/api/visual-api.spec.ts
- visual-js/visual-snapshots/test/api/worker/pdf-page-snapshot-uploader.spec.ts
- visual-js/visual-snapshots/test/app/__snapshots__/pdf-handler.spec.ts.snap
- visual-js/visual-snapshots/test/app/pdf-file-loader.spec.ts
- visual-js/visual-snapshots/test/app/pdf-handler.spec.ts
- visual-js/visual-snapshots/test/mock-file-extractor.ts
- visual-js/visual-snapshots/test/mock-logger.ts
- visual-js/visual-snapshots/test/system-helpers.ts
- visual-js/visual-snapshots/test/utils/glob.spec.ts
- visual-js/visual-snapshots/test/utils/pool.spec.ts
- visual-js/visual-snapshots/test/utils/templates.spec.ts
- Do not create a build when there are no files to process
- Log files to be processed
- Extra test
- Divide test helpers into files
- Add tests which check that we only look for pdf files
> [no-ticket] Do not create a build when there are no files to process

- visual-java/pom.xml
- visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
- visual-java/src/main/java/com/saucelabs/visual/graphql/CreateSnapshotMutation.java
- visual-java/src/main/java/com/saucelabs/visual/graphql/CreateSnapshotUploadMutation.java
- visual-java/src/main/java/com/saucelabs/visual/graphql/GraphQLClient.java
- visual-java/src/main/java/com/saucelabs/visual/utils/CapabilityUtils.java
Adds local selenium grid support to our Java SDK. This should automatically determine if this is a sauce session (In most instances) and either run our capture tooling from our backend or the simplified solution from our SDK directly using Selenium APIs.
Currently this omits the following:
- Full page screenshot support
- Element based ignore regions
- element / page clipping
- dom capture (and therefore selective diffing)
> [Java] Add local selenium grid support for basic snapshots

- visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
`getHeight()` is passed instead of `getY()` to the `y` parameter.
> [no-ticket] fix invalid value being passed to ignoreChangesFor

- visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
`getIgnoreRegions()` is checked against `null` instead of `getRegions()` when retrieving regions.
> [no-ticket] visual-java: fix invalid check for options.getRegions

- visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
- visual-java/src/main/java/com/saucelabs/visual/exception/InvalidIgnoreSelectorException.java
- visual-java/src/main/java/com/saucelabs/visual/exception/InvalidSelectorException.java
- visual-java/src/main/java/com/saucelabs/visual/exception/InvalidVisualRegionException.java
- visual-java/src/main/java/com/saucelabs/visual/exception/InvalidWebElementException.java
- visual-java/src/main/java/com/saucelabs/visual/model/VisualRegion.java
- visual-java/src/main/java/com/saucelabs/visual/utils/BulkDriverHelper.java
> Issue : INT-282
Adds retrieving data from browser in bulk if possible, such as:
* `getRect()`
* `isDisplayed()`
* `findElement`
Additionally, adds some specialized exceptions containing the faulting object. This is done because sometimes tracking the index of the faulting object would have been troublesome.
> [INT-282] visual-java: retrieve data from browser in bulk when possible

- .github/workflows/java-build.yml
- .github/workflows/java-release.yml
- visual-java/pom.xml
- visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
- visual-java/src/main/java/com/saucelabs/visual/utils/ImageHelpers.java
- visual-java/src/main/java/com/saucelabs/visual/utils/Window.java
- visual-java/src/test/java/com/saucelabs/visual/integration/IgnoreRegionsIT.java
- visual-java/src/test/java/com/saucelabs/visual/integration/IntegrationBase.java
- visual-java/src/test/java/com/saucelabs/visual/integration/__snapshots__/IgnoreRegionsIT.snap
Adds support for Full Page Screenshots using BiDi on a local selenium instance. Requires use of a `webSocketUrl: true` capability in order to be functional.
> [Java] FPS support for local grid using bidi

- visual-dotnet/SauceLabs.Visual/Region.cs
Default region inaccessible with existing logic
Get an error if Region is not provided
> [C#] fix logic so the default region can be accessible

- visual-dotnet/SauceLabs.Visual.IntegrationTests/IntegrationTestAttribute.cs
- visual-dotnet/SauceLabs.Visual.IntegrationTests/LoginPage.cs
- visual-dotnet/SauceLabs.Visual.IntegrationTests/LoginPageConcurrent.cs
- visual-dotnet/SauceLabs.Visual.IntegrationTests/Utils.cs
- visual-dotnet/SauceLabs.Visual/ConcurrentVisualClient.cs
- visual-dotnet/SauceLabs.Visual/Utils/WebDriverMetadata.cs
- visual-dotnet/SauceLabs.Visual/Utils/WebDriverMetadataCache.cs
- visual-dotnet/SauceLabs.Visual/VisualClient.cs
- visual-dotnet/SauceLabs.Visual/VisualClientBase.cs
> Issue : INT-324
If you want to use `VisualClient` concurrently with multiple drivers, there's no current way to do so.
One could create multiple `VisualClient`s, but this approach has an issue with closing the clients. Every client by design will have the same build, and closing any one of them will cause others to start failing, as they will submit their snapshots to an already closed build.
To allow for using multiple drivers with a single build, you can create `VIsualClient` without specifying a `WebDriver` instance. You specify it then in `VisualCheck` method. Using the `VisualCheck` method without specifying a `WebDriver` instance will throw an exception if the `VisualClient` instance was initialized without a driver.
The `VisualClient` instance has to be created once and disposed …
> [INT-324] Allow to pass WebDriver to the VisualCheck method
