visual-dotnet/SauceLabs.Visual/VisualClient.cs

Test is the opposite of expectation.

fix: CustomID check

---

visual-dotnet/SauceLabs.Visual/VisualClient.cs

The region used is not the one passed by the user.

fix: Apply configurable region

---

visual-dotnet/SauceLabs.Visual/GraphQL/CreateSnapshotFromWebDriverIn.cs
visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
visual-dotnet/SauceLabs.Visual/VisualClient.cs

> Issue : IRIS-855
Add support for `clipSelector`.

Add support for clipSelector

---

visual-dotnet/README.md

Correct examples in README.md

---

visual-dotnet/SauceLabs.Visual/FullPageConfig.cs
visual-dotnet/SauceLabs.Visual/GraphQL/CreateSnapshotFromWebDriverIn.cs
visual-dotnet/SauceLabs.Visual/GraphQL/FullPageConfigIn.cs
visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
visual-dotnet/SauceLabs.Visual/VisualClient.cs

.Net - Add support for Full Page Screenshot

---

.github/workflows/python-build.yml
.github/workflows/python-release.yml
visual-python/.bumpversion.toml
visual-python/.gitignore
visual-python/README.md
visual-python/pyproject.toml
visual-python/requirements-dev.txt
visual-python/requirements.txt
visual-python/requirements/build.txt
visual-python/requirements/dev.txt
visual-python/requirements/user.txt

Adds pipelines & configuration for publishing the package to PyPI. 

Add publishing to PyPI

---

visual-python/src/saucelabs_visual/client.py
visual-python/src/saucelabs_visual/frameworks/robot.py

Fetches and caches session metadata automatically when using `create_snapshot_from_webdriver`

[Python] Cache & fetch metadata automatically

---

visual-python/src/saucelabs_visual/client.py

Python SDK should use the same env vars as others

Align python env vars

---

.github/workflows/java-build.yml

Adds build pipeline for java sdk

Build pipeline for Java SDK

---

visual-python/src/saucelabs_visual/frameworks/robot.py

Fix parsing for full page config from robot keyword

---

visual-python/pyproject.toml
visual-python/requirements/user.txt
visual-python/src/saucelabs_visual/client.py

Exchanges the request library used as the GQL transport.

[Python] Swap out library used for making http requests

---

.github/workflows/python-build.yml
.github/workflows/python-release.yml
visual-python/pyproject.toml
visual-python/requirements/dev.txt
visual-python/requirements/user.txt
visual-python/src/saucelabs_visual/client.py
visual-python/src/saucelabs_visual/frameworks/robot.py
visual-python/src/saucelabs_visual/regions.py
visual-python/src/saucelabs_visual/typing.py
visual-python/src/saucelabs_visual/utils.py
visual-python/tests/test_utils.py

Adds a number of enhancements to the Python binding and Robot Framework integration.
- Adds ignore region selector & web element parsing for Selenium in Robot
- Adds method & keyword for getting build status and outputting the results in a CLI-compatible table
- Adds build logging for build creation and shutdown
- Sets up pytest and adds a handful of unit tests for new utils

Python Updates / Additions

---

visual-python/README.md

Adds link to sauce docs website for the python binding.

Add link to docs website in readme

---

visual-python/src/saucelabs_visual/client.py
visual-python/src/saucelabs_visual/frameworks/robot.py

- Resolves an issue where SeleniumLibrary could not be aliased when imported in a Robot resources file
- Create the Visual Client dynamically when attempting to access it for the first time instead of during initialization

[Python] Updates / Fixes

---

visual-dotnet/SauceLabs.Visual/BuildFactory.cs
visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/utils/EnvironmentVariables.java

> Issue : IRIS-936
Fix build customizing environment variable handling for java and dotnet sdk.
- Breaking change (fix or feature that would cause existing functionality to change)

[fix] Env var precedence

---

visual-python/.bumpversion.toml
visual-python/requirements/dev.txt
visual-python/src/saucelabs_visual/client.py

Add the userAgent following the conventions we already have in others.

python: Add userAgent info

---

visual-dotnet/SauceLabs.Visual/Models/SelectiveRegion.cs

fix: C# / EnabledRegion -> EnabledFor

---

visual-js/yarn.lock

Update to 0.4.0

---

.github/workflows/dotnet-build.yml
.github/workflows/java-build.yml
.github/workflows/js-build.yml
.github/workflows/python-build.yml

Avoid running both PR & branch pipelines.

Disable branch build except for main

---

visual-js/.changeset/loud-timers-check.md
visual-js/visual/package.json
visual-js/visual/schema/__generated__/schema.graphql
visual-js/visual/src/graphql/__generated__/graphql.ts
visual-js/visual/src/types.ts

fps deprecate some options

---

visual-js/.changeset/gold-clocks-try.md
visual-js/visual-cypress/src/commands.ts
visual-js/visual-cypress/src/index.ts
visual-js/visual-cypress/src/types.ts
visual-js/visual/src/selective-region.ts
visual-js/yarn.lock

Add support for Selective Region in Cypress

---

visual-java/src/main/graphql/visual/schema.graphqls
visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/graphql/CreateSnapshotFromWebDriverMutation.java
visual-java/src/main/java/com/saucelabs/visual/model/VisualRegion.java

Adds WebElement support to the java bindings to reduce frontend calculation.

[Java] Add backend WebElement support

---

.github/workflows/dotnet-build.yml
visual-dotnet/Dockerfile
visual-dotnet/SauceLabs.Visual.IntegrationTests/IntegrationTestAttribute.cs
visual-dotnet/SauceLabs.Visual.IntegrationTests/LoginPage.cs
visual-dotnet/SauceLabs.Visual.IntegrationTests/SauceLabs.Visual.IntegrationTests.csproj
visual-dotnet/SauceLabs.Visual.IntegrationTests/Utils.cs
visual-dotnet/SauceLabs.Visual.sln

Adds env var integration tests to C# build workflow
> Issue : IRIS-1050

Dotnet env var tests

---

visual-dotnet/SauceLabs.Visual/Models/SelectiveRegion.cs

[C#] Remove Obsolete for SelectiveRegion

---

visual-js/.changeset/quick-rocks-bake.md
visual-js/visual-cypress/src/index.ts
visual-js/yarn.lock

Fixes the bug where fetching build when using external build ID was resulting in error.

Cypress fix external build

---

visual-python/src/saucelabs_visual/client.py

[Python] Create build with custom ID when not created externally

---

.github/workflows/js-release.yml
visual-js/replace_pkg_version.sh

> Issue : IRIS-1076
Fixes the broken behavior of setting PKG_VERSION in js SDKs 

Fix js SDK client version setting in release pipeline

---

.github/workflows/js-release.yml

Trigger js release on push to main branch

---

visual-java/src/main/java/com/saucelabs/visual/DataCenter.java
visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/graphql/GraphQLClient.java
visual-java/src/main/java/com/saucelabs/visual/utils/EnvironmentVariables.java
visual-java/src/test/java/com/saucelabs/visual/integration/LoginPageIT.java

> Issue : IRIS-1069
Bring SAUCE_REGION support to Java SDK

[java] Support SAUCE_REGION

---

visual-js/.changeset/config.json
visual-js/.changeset/small-mails-think.md
visual-js/visual-cypress/src/index.ts
visual-js/visual-wdio/src/SauceVisualService.ts
visual-js/visual/codegen.ts
visual-js/visual/src/cli/build.spec.ts
visual-js/visual/src/cli/build.ts
visual-js/visual/src/graphql/__generated__/graphql.ts

- Return snapshotId from wdio `sauceVisualCheck` commands to allow using in follow up assertions
- Fix changed file checks in changesets
- Update the codegen types for dates & UUID instead of any

[JS] Codegen & WDIO Updates

---

visual-js/.changeset/cyan-pants-watch.md
visual-js/visual/src/cli/build.spec.ts
visual-js/visual/src/cli/build.ts
visual-js/yarn.lock

[WDIO] Prioritize custom id > build id when present

---

visual-dotnet/README.md
visual-java/README.md
visual-js/visual-cypress/README.md
visual-js/visual-nightwatch/README.md
visual-js/visual-storybook/CHANGELOG.md
visual-js/visual-storybook/README.md
visual-js/visual-wdio/README.md
visual-python/README.md

> Issue : IRIS-1083
Add build, lint and test instructions to SDK readme files

Readme dev instructions

---

.github/workflows/python-build.yml
tests/env-vars-custom-id.spec.ts
visual-python/Dockerfile
visual-python/integration-tests/robot/__init__.robot
visual-python/integration-tests/robot/integration/login.robot

> Issue : IRIS-1052
Adds environment variable tests for python binding

Python env var tests

---

visual-js/.changeset/wise-plants-rest.md
visual-js/visual-wdio/integration-tests/specs/login.spec.ts
visual-js/visual-wdio/integration-tests/tsconfig.json
visual-js/visual-wdio/src/SauceVisualService.ts

> Issue : IRIS-1033
Adds missing clip element support for wdio

clip element support for wdio

---

visual-java/src/main/java/com/saucelabs/visual/CheckOptions.java
visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/graphql/CreateSnapshotFromWebDriverMutation.java
visual-java/src/test/java/com/saucelabs/visual/VisualApiTest.java
visual-java/src/test/java/com/saucelabs/visual/integration/LoginPageIT.java

> Issue : IRIS-1140
Adds clip to element support to java.

[java] clip element support

---

visual-js/visual-nightwatch/Dockerfile
visual-js/visual-nightwatch/integration-tests/nightwatch/external/saucedemo.ts
visual-js/visual-nightwatch/integration-tests/nightwatch/tests/saucedemo.ts
visual-js/visual-nightwatch/integration-tests/package.json
visual-js/visual-nightwatch/src/nightwatch/commands/sauceVisualCheck.ts
visual-js/visual-nightwatch/src/types.ts

> Issue : IRIS-1143
clipSelector support for Nightwatch

[nightwatch] clip element support

---

visual-js/.changeset/brave-days-drive.md
visual-js/visual-wdio/package.json
visual-js/visual-wdio/src/SauceVisualService.ts
visual-js/visual-wdio/src/index.ts
visual-js/yarn.lock

Adds support for baseline overrides to WDIO

[WDIO] Support baseline overrides

---

visual-js/.changeset/blue-turkeys-decide.md
visual-js/visual/src/documents/buildStatus.graphql

Clean deprecated fields

---

visual-js/.changeset/tidy-penguins-talk.md
visual-js/visual/src/cli.ts
visual-js/visual/src/cli/baselines.ts
visual-js/visual/src/cli/common-options.ts

Enable merge baselines command

---

visual-js/replace_pkg_version.sh

Add Playwright to JS releases

---

visual-js/.changeset/dry-timers-reply.md
visual-js/visual-playwright/src/api.ts
visual-js/visual-playwright/src/playwright.ts
visual-js/visual-storybook/src/config.ts
visual-js/yarn.lock

Fixes passing of variables into storybook jest config by only parsing & bootstrapping variables once.

[Storybook] Correct passing global setup variables

---

visual-js/.changeset/lucky-ladybugs-allow.md
visual-js/visual-nightwatch/Dockerfile
visual-js/visual-nightwatch/src/nightwatch/commands/sauceVisualCheck.ts
visual-js/visual-nightwatch/src/types.ts
visual-js/visual-wdio/Dockerfile
visual-js/visual-wdio/src/SauceVisualService.ts
visual-js/visual-wdio/src/guarded-types.ts
visual-js/visual/src/graphql/__generated__/graphql.ts
visual-js/visual/src/types.ts
visual-js/visual/src/utils.spec.ts
visual-js/visual/src/utils.ts

expose scrollElement options for native fps

add scrollElement fps option for native apps

---

visual-espresso/gradle/libs.versions.toml
visual-espresso/visual/build.gradle
visual-espresso/visual/src/main/java/com/saucelabs/visual/graphql/GraphQLClient.java

Apollo java client was causing problems with gradle 7 projects. 
Downgraded the apollo runtime to 3.x and switched to using rx3-java instead of the java client.

IRIS-1320 Gradle 7 support

---

visual-js/.changeset/unlucky-poems-search.md
visual-js/visual-wdio/src/SauceVisualService.ts
visual-js/yarn.lock

Adds the missing `customId` support during build creation in WDIO

[WDIO] Fix missing custom ID support in WDIO

---

visual-js/.changeset/rude-weeks-sleep.md
visual-js/visual-wdio/src/SauceVisualService.ts
visual-js/visual/src/types.ts

wdio - clipping for native fps

wdio - clipping for native fps

---

visual-java/src/main/graphql/visual/schema.graphqls
visual-java/src/main/java/com/saucelabs/visual/model/FullPageScreenshotConfig.java

> Issue : IRIS-1430
Add support for ScrollOption for Java

Add ScrollOption support for Java

---

visual-dotnet/SauceLabs.Visual/FullPageConfig.cs
visual-dotnet/SauceLabs.Visual/GraphQL/CreateSnapshotFromWebDriverIn.cs
visual-dotnet/SauceLabs.Visual/VisualCheckOptions.cs
visual-dotnet/SauceLabs.Visual/VisualClientBase.cs
visual-java/src/main/java/com/saucelabs/visual/CheckOptions.java
visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/graphql/CreateSnapshotFromWebDriverMutation.java
visual-java/src/main/java/com/saucelabs/visual/model/FullPageScreenshotConfig.java
visual-js/.changeset/tall-yaks-lick.md
visual-js/visual-nightwatch/src/nightwatch/commands/sauceVisualCheck.ts
visual-js/visual-nightwatch/src/types.ts
visual-js/visual-wdio/src/SauceVisualService.ts
visual-js/visual/src/graphql/__generated__/graphql.ts
visual-js/visual/src/types.ts
visual-python/src/saucelabs_visual/client.py
visual-python/src/saucelabs_visual/frameworks/robot.py
visual-python/src/saucelabs_visual/typing.py

expose hide scroll bars option in check method

hideScrollBars for wdio, nightwatch

---

visual-js/package-lock.json
visual-js/visual-snapshots/package.json
visual-js/visual-snapshots/src/api/visual-snapshots-api.ts
visual-js/visual-snapshots/src/app/pdf-handler.ts
visual-js/visual-snapshots/src/app/worker/pdf-page-snapshot-uploader.ts
visual-js/visual-snapshots/src/app/worker/worker.ts
visual-js/visual-snapshots/src/commands/options.ts
visual-js/visual-snapshots/src/commands/pdf.ts
visual-js/visual-snapshots/src/index.ts
visual-js/visual-snapshots/src/logger.ts
visual-js/visual-snapshots/test/api/__snapshots__/visual-api.spec.ts.snap
visual-js/visual-snapshots/test/api/visual-api.spec.ts
visual-js/visual-snapshots/test/api/worker/pdf-page-snapshot-uploader.spec.ts
visual-js/visual-snapshots/test/app/pdf-handler.spec.ts
visual-js/visual-snapshots/test/helpers.ts

> Issue : INT-1
Adds `pino` logger with `pino-pretty` instead of `console`.

[INT-1] visual-snapshots: add pino logger

---

visual-js/.changeset/odd-shrimps-provide.md
visual-js/package-lock.json
visual-js/visual-snapshots/package.json

update package-lock
Corrects the dependency version for `visual-snapshots` to use the same version from the local workspace.

Update dependency version for visual-snapshots

---

visual-js/.changeset/spotty-seas-argue.md

Bump js package versions to use hover fix in web full page screenshot

fix hover effect for web full page screenshot

---

visual-java/pom.xml

manually bump java sdk version

java fix full page screenshot hover effect issue

---

visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/graphql/GraphQLClient.java

Allows adjusting the proxy settings for the SDK via a config option instead of using environment variables.
Example usage:
```java
VisualApi visual = new VisualApi.Builder(
driver,
username,
accessKey
)
.withBuild("Sauce Demo Test")
.withRequestConfig(
RequestConfig
.custom()
.setProxy(HttpHost.create("http://my-proxy.host"))
.build()
)
.build();
```

Add requestConfig option for adjusting proxy / timeout settings in SDK

---

visual-js/visual-snapshots/src/api/visual-snapshots-api.ts
visual-js/visual-snapshots/src/app/pdf-files-snapshot-uploader.ts
visual-js/visual-snapshots/src/app/worker/pdf-page-snapshot-uploader.ts
visual-js/visual-snapshots/src/app/worker/worker-pool-pdf-snapshot-uploader.ts
visual-js/visual-snapshots/src/commands/options.ts
visual-js/visual-snapshots/test/app/pdf-handler.spec.ts

Create defaults for: build name, suite name, test name, snapshot name

[INT-201] reasonable default values

---

visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/graphql/GraphQLClient.java

Adds DOM capture / upload for local selenium clients.

[Java/Local] Add DOM capture 

---

visual-java/src/main/java/com/saucelabs/visual/VisualApi.java
visual-java/src/main/java/com/saucelabs/visual/model/WindowScroll.java

> Issue : [INT-251](https://saucedev.atlassian.net/browse/INT-251)
Add support for ignore regions for local snapshots.
Ignore region coordinates are offset by the current page scroll.
[INT-251]: https://saucedev.atlassian.net/browse/INT-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INT-251] Support ignore regions for local snapshots

---

visual-java/src/main/java/com/saucelabs/visual/VisualApi.java

Skips ignore regions not intersecting with the viewport. The viewport may be a clipped element.

[no-ticket] [Java/Local] visual-java: do not include ignore regions outside of image

---

.github/workflows/java-release.yml
visual-java/pom.xml

[Java] Exchange ossrh with sonatype central publishing

---

.github/workflows/js-build.yml
.github/workflows/js-release.yml
visual-js/.changeset/odd-sheep-run.md
visual-js/.npmrc
visual-js/package-lock.json
visual-js/visual-nightwatch/Dockerfile
visual-js/visual-playwright/Dockerfile
visual-js/visual-playwright/src/api.spec.ts
visual-js/visual-snapshots/README.md
visual-js/visual-snapshots/package.json
visual-js/visual-storybook/Dockerfile
visual-js/visual-wdio/Dockerfile
visual-js/visual/src/graphql/__generated__/graphql.ts

Updates pdf-to-img to include Node >= 20 support, as well as additional precompiled binaries various OSes in the canvas dependency.

[visual-snapshots] Bump pdf-to-img
